---
apiVersion: apps/v1           # API version
kind: Deployment              # Type of kubernetes resource
metadata:
  name: users-mysql  # Name of the kubernetes resource
  labels:                     # Labels that will be applied to this resource
    app: users-mysql
spec:
  replicas: 2                 # No. of replicas/pods to run in this deployment
  selector:
    matchLabels:              # The deployment applies to any pods mayching the specified labels
      app: users-mysql
  template:                   # Template for creating the pods in this deployment
    metadata:
      labels:                 # Labels that will be applied to each Pod in this deployment
        app: users-mysql
    spec:                     # Spec for the containers that will be run in the Pods
      containers:
      - name: users-mysql
        image: aymensegni/users-mysql:v0.0.1
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 8086 # The port that the container exposes
        resources:
          limits:
            cpu: 0.1
            memory: "100Mi"
        env:                  # Environment variables supplied to the Pod
        - name: SPRING_DATASOURCE_USERNAME # Name of the environment variable
          valueFrom:          # Get the value of environment variable from kubernetes secrets
            secretKeyRef:
              name: mysql-user-pass
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-user-pass
              key: password
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: mysql-db-url
              key: url
---
apiVersion: v1                # API version
kind: Service                 # Type of the kubernetes resource
metadata:
  name: users-mysql    # Name of the kubernetes resource
  labels:                     # Labels that will be applied to this resource
    app: users-mysql
spec:
  type: NodePort             # The service will be exposed by opening a Port on each node and proxying it.
  selector:
    app: users-mysql   # The service exposes Pods with label `app=polling-app-server`
  ports:                      # Forward incoming connections on port 8080 to the target port 8080
  - name: http
    port: 8086
    targetPort: 8086
